### PR TITLE
Modal box with placeholders

### PR DESCRIPTION
**Pull request by reyna-abhyankar**
It is currently opened on a button click.

### CODE REVIEW

**Comment by reyna-abhyankar** [comment]
Position of "$$$" label at the top right corner and labels on "add to cart" button are not correct when window is resized (made smaller) -- _not a priority_

**Comment by reyna-abhyankar** [comment]
Home route link is fixed in this merge.

**Review by declansullivan — APPROVED** [review]
lgtm

**Comment by wes-chen** [comment]
good job team!

**Review by dhrvsood — APPROVED** [review]

**Pull request merged**
