### PR TITLE
Admin login functionality with cookies

### LINKED ISSUE #28: Implement admin login system
Admins should be able to log in and see the orders made, as well as be able to select that orders have been fulfilled.

### PR DESCRIPTION
**Pull request by dhrvsood**
Closes #28.

### CODE REVIEW

**Comment by reyna-abhyankar** [comment]
Lint and merge errors

**Comment by declansullivan** [comment]
Screen Shot 2020-05-26 at 11 02 13 AM
Error when loading menu page, is this just on my end?

**Comment by declansullivan** [comment]
Also, clicking login doesn't seem to do anything for me, just adds a hash at the end of the link, eg: localhost:4000 -> localhost:4000/#.

**Comment by dhrvsood** [comment]
I think cart isn't working because you need to have a local version of the database on compass. Login should be functional from all screens because it's in the navbar, does it work when you are in the menu?

**Review by declansullivan — APPROVED** [review]

**Review by reyna-abhyankar — APPROVED** [review]

**Pull request merged**
